ClassroomManagementApplication/ClassroomManagementApplication/Models/Classroom.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassroomManagementApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Classroom()
        {
            this.BehaviorType = new HashSet<BehaviorType>();
            this.Student = new HashSet<Student>();
        }
    
        public decimal classID { get; set; }
        public Nullable<System.DateTime> semesterStart { get; set; }
        public Nullable<System.DateTime> semesterEnd { get; set; }
        public Nullable<decimal> teacherID { get; set; }
        public string classCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BehaviorType> BehaviorType { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student { get; set; }
    }
}

ClassroomManagementApplication/ClassroomManagementApplication/Controllers/ClassroomController.cs
using ClassroomManagementApplication.Models;
using System;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Linq;

namespace ClassroomManagementApplication.Controllers {
    public class ClassroomController : Controller {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ClassroomController() {
        }

        public ClassroomController(ApplicationUserManager userManager, ApplicationSignInManager signInManager) {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager {
            get {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager {
            get {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set {
                _userManager = value;
            }
        }

        // GET: Classroom?classcode={classcode}
        [Authorize]
        public ActionResult Index(string classcode) {
            Teacher t = UserBinding.getTeacher(User.Identity.GetUserId());
            Classroom cr = ClassroomBinding.GetClassroomFromCode(classcode);
            if(cr == null || t == null || classcode == null)
            {
                //TODO add viewbag error?
                return RedirectToAction("Index", "Home");
            }
            ClassroomIndexViewModel model = new ClassroomIndexViewModel();
            model.Classroom = cr;
            model.Teacher = t;
            model.Students = cr.Student.ToList();

            return View(model);
        }

        // GET: Classroom/Join
        [Authorize]
        public ActionResult Join() {


            return View();
        }

        // POST: Classroom/Join
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Join(string classCode) {
            var user = User.Identity.GetUserId();
            Classroom cr = ClassroomBinding.GetClassroomFromCode(classCode);
            if(user == null || cr == null || classCode == null)
            {
                ViewBag.ErrorMessage = "Error: There was an issue joining a classroom.";
                return View();
            }
            UserBinding.JoinClass(user, classCode);
            return View();
        }

        // GET: Classroom/Add
        [Authorize]
        public ActionResult Add() {
            return View();
        }

        //POST: Classroom/Add
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Add(DateTime start, DateTime end, string classcode) {
            Teacher t = UserBinding.getTeacher(User.Identity.GetUserId());
            //TODO clean parameters
            if (t == null) {
                return RedirectToAction("Index", "Home");
            }
            if (ClassroomBinding.GetClassroomFromCode(classcode)?.classID != null) {
                ViewBag.ErrorMessage = "Error: please enter a unique class code.";
                return View();
            }
            var classroom = new Classroom {
                classID = ClassroomBinding.GenerateClassId(),
                semesterStart = start,
                semesterEnd = end,
                classCode = classcode,
                teacherID = t.TeacherID
            };
            ClassroomBinding.SaveRoom(classroom);
            return RedirectToAction("Index", "Home");
        }
    }


}

ClassroomManagementApplication/ClassroomManagementApplication/Views/Classroom/Add.cshtml
@model ClassroomManagementApplication.Models.Classroom
@{
    ViewBag.Title = "Add a Classroom";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $(".datepicker").datepicker();
        });
    </script>

}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">


<h2>Add a new Classroom</h2>
<h3>@ViewBag.ErrorMessage</h3>

@using (Html.BeginForm("Add", "Classroom", FormMethod.Post))
{

    @Html.AntiForgeryToken()

    <dt>Class Code:</dt>
    <dd>
        <input name="classcode" type="text" />
    </dd>
    <dt>Semester Start:</dt>
    <dd>
        <input name="start" type="text" class="datepicker" />
    </dd>
    <dt>Semester End:</dt>
    <dd>
        <input name="end" type="text" class="datepicker" />
    </dd>

    <input type="submit" value="Add Class" />
}

ClassroomManagementApplication/ClassroomManagementApplication/Views/Classroom/AddClassroom.cshtml
@{
    ViewBag.Title = "AddClassroom";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add a new Classroom</h2>

ClassroomManagementApplication/ClassroomManagementApplication/Views/Classroom/Index.cshtml
@model ClassroomManagementApplication.Models.ClassroomIndexViewModel
@using ClassroomManagementApplication.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Classroom: @Model.Classroom.classCode</h1>
<p class="text-center">@Model.Classroom.semesterStart.Value.ToShortDateString() - @Model.Classroom.semesterEnd.Value.ToShortDateString()</p>
<p class="text-center">@Html.ActionLink("Add a behavior type to the rubric", "AddType", "Behavior", new { classcode = Model.Classroom.classCode }, new { @style = "color:black" })</p>

@if (Model.Students.Count > 0) {
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>First Name</th>
                <th>Username</th>
                <th>Points Total</th>
                <th>Prize Requested</th>
                <th>Add Behavior</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Student s in Model.Students) {
                <tr>
                    <td>@s.studentFirst</td>
                    <td>@s.studentUsername</td>
                    <td>@UserBinding.GetPoints(s.StudentID)</td>
                    <td>@ClassroomBinding.IsRequested(s.StudentID)</td>
                    <td>@Html.ActionLink("Add Behavior", "Add", "Behavior", new { studentuserID = s.UserID, classcode = Model.Classroom.classCode }, new { @style = "color:black" })</td>
                </tr>
            }

        </tbody>

    </table>
}

ClassroomManagementApplication/ClassroomManagementApplication/Views/Classroom/Join.cshtml
@{
    ViewBag.Title = "Join";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Join a Classroom</h2>
<h3>@ViewBag.ErrorMessage</h3>

@using (Html.BeginForm("Join", "Classroom", "FormMethod.Post"))
{
    @Html.AntiForgeryToken()
    <dt>Class Code:</dt>
    <dd><input name="classCode" type="text"/></dd>
    <input type="submit" value="Join Class"/>
}