ClassroomManagementApplication/ClassroomManagementApplication/Models/BehaviorType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassroomManagementApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehaviorType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BehaviorType()
        {
            this.BehaviorPerformed = new HashSet<BehaviorPerformed>();
        }
    
        public decimal behaviorID { get; set; }
        public string behaviorTitle { get; set; }
        public string behaviorDescription { get; set; }
        public Nullable<decimal> pointValue { get; set; }
        public Nullable<decimal> classID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BehaviorPerformed> BehaviorPerformed { get; set; }
        public virtual Classroom Classroom { get; set; }
    }
}

ClassroomManagementApplication/ClassroomManagementApplication/Controllers/BehaviorController.cs
using ClassroomManagementApplication.Models;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;

namespace ClassroomManagementApplication.Controllers
{
    public class BehaviorController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public BehaviorController()
        {
        }

        public BehaviorController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //// GET: Behavior
        //public ActionResult Index()
        //{
        //    return View();
        //}

        //GET: Behavior/Add
        [Authorize]
        public ActionResult Add(string studentuserID, string classcode)
        {
            if (classcode == null ) {
                //error message
                return RedirectToAction("Classroom", "Index", new {classcode = classcode});
            }
            Classroom cr = ClassroomBinding.GetClassroomFromCode(classcode);
            if(cr == null) {
                //error message
                return RedirectToAction("Classroom", "Index", new { classcode = classcode });
            }

            NewBehaviorViewModel model = new NewBehaviorViewModel() {
                ClassCode = classcode,
                StudentUserID = User.Identity.GetUserId()
            };
            model.BehaviorTypes = new List<SelectListItem>();
            List<BehaviorType> bts = cr.BehaviorType.ToList();
            foreach (BehaviorType bt in bts) {
                model.BehaviorTypes.Add(new SelectListItem { Text = bt.behaviorTitle, Value = bt.behaviorID.ToString()});
            }
            return View(model);
        }

        //POST: Behavior/Add
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Add(NewBehaviorViewModel model, FormCollection form)
        {
            if (!ModelState.IsValid || model.DatePerformed == null || model.BehaviorTypePerformedID == null) {
                return RedirectToAction("Home", "Index");
            }
            Student student = UserBinding.getStudent(model.StudentUserID);
            if(student.classID == null) {
                return RedirectToAction("Home", "Index");
            }

            BehaviorType bt = ClassroomBinding.GetBehaviorType((decimal)student.classID, Convert.ToDecimal(model.BehaviorTypePerformedID));
            UserBinding.AddBehaviorToStudent(student, bt, model.DatePerformed);
            return RedirectToAction("Index","Classroom", new { classcode = ClassroomBinding.GetClassroomFromID(student.classID).classCode });
        }

        //GET: Behavior/AddType
        [Authorize]
        public ActionResult AddType(string classcode)
        {
            AddTypeViewModel model = new AddTypeViewModel();
            model.ClassCode = classcode;
            return View(model);
        }

        //POST: Behavior/AddType
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult AddType(AddTypeViewModel type)
        {
            //TODO null check
            var behavior = new BehaviorType
            {
                behaviorID = BehaviorBinding.GenerateBehaviorId(),
                behaviorTitle = type.Title,
                behaviorDescription = type.Description,
                pointValue = type.PointValue,
                classID = ClassroomBinding.GetClassroomFromCode(type.ClassCode).classID
            };

            BehaviorBinding.SaveBehavior(behavior);
            return View();
        }
    }
}

ClassroomManagementApplication/ClassroomManagementApplication/Views/Behavior/Add.cshtml
@model ClassroomManagementApplication.Models.NewBehaviorViewModel
@using ClassroomManagementApplication.Models
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $(".datepicker").datepicker();
        });
    </script>
}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">

<h2>Record a new behavior </h2>

@using (Html.BeginForm("Add", "Behavior", FormMethod.Post)) {
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.StudentUserID);
    @Html.HiddenFor(m => m.ClassCode);
    <dt>Date of Occurence</dt>
    <dd>
        @Html.TextBoxFor(m => m.DatePerformed, new { @class = "datepicker" })
    </dd>

    <dt>Select which behavior:</dt>
    <dd>
        @Html.DropDownListFor(m => m.BehaviorTypePerformedID, Model.BehaviorTypes)
    </dd>

    <input type="submit" value="Record Behavior" />
}

ClassroomManagementApplication/ClassroomManagementApplication/Views/Behavior/AddType.cshtml
@model ClassroomManagementApplication.Models.AddTypeViewModel
@{
    ViewBag.Title = "Add a Behavior";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Add a New Behavior Type to the Rubric</h2>

@using (Html.BeginForm("AddType", "Behavior", FormMethod.Post))
{

    @Html.AntiForgeryToken()

    <dt>Behavior Title:</dt>
    <dd>
        @Html.TextBoxFor(m => m.Title)

    </dd>
    <dt>Behavior Description:</dt>
    <dd>
        @Html.TextBoxFor(m => m.Description)

    </dd>
    <dt>Point Value:</dt>
    <dd>
        @Html.TextBoxFor(m => m.PointValue)
    </dd>
    @Html.HiddenFor(m => m.ClassCode);

    <input type="submit" value="Add Behavior" />
}